### ISSUE TITLE
JSON file example

### ISSUE THREAD

**Issue by kishan19** [AutoViML/AutoViz#32]
Is there an example where I could use a JSON file with AutoVIZ, seem to be running into errors. Would be good to have a sample file that works.

**Comment by AutoViML** [comment]
The reason I don't have an example is very simple -> JSON's are very hard
to visualize since they may not have a consistent structure
Instead if you load the JSON into a Pandas DataFrame you will have a
consistent structure (columns) to the data and then you can feed it to
AutoViz.
Try that approach first and see if it works.
Ram

**Comment by username7171** [comment]
Understand that it doesn't have a consistent structure, so it is hard.

But on the main page, you said you could feed JSON into autoviz, however seems all JSON will produce the error. 

Maybe we could remove that statement until we find some good way to parse the JSON file.

Thanks!

**Comment by AutoViML** [comment]
Hi @sunset1234321 👍 

I have created a Kaggle Notebook to show how you can create charts using JSON files. If you feel that this functionality should be in AutoViz directly, then I can incorporate it. Take a look at this notebook:
[Kaggle Notebook on JSON file](https://www.kaggle.com/rsesha/autoviz-on-json-file-and-saving-as-html)

Hope this helps,
AutoViML
