### ISSUE TITLE
`html` format file output

### ISSUE THREAD

**Issue by beobest2** [AutoViML/AutoViz#34]
Most of the other EDA tools support `html` format file output. 
Do you have any plans to support `html`  format file output function, taking the output path of the file as an argument? 
Thank you.

**Comment by AutoViML** [comment]
I am working on this - I'll let you know as soon as it is ready.
Ram

**Comment by AutoViML** [comment]
beobest2  : At the moment, since I am planning on porting AutoViz to other plotting methods, I am busy and hence won't be able to focus on HTML file format. I will let you know if this changes. If you or someone wants to work on it as a project, I can guide you easily.
Ram

**Comment by AutoViML** [comment]
Hi @beobest2 👍 
AutoViz now allows you to save all charts in HTML format. They are even dynamic HTML charts since they have widgets that allow you to change them. Take a look at the main README page to see how it works.

I will also add examples in the Examples page so you can see it in action.

Hope this helps,
AutoViML team
