### ISSUE TITLE
exporting the report

### ISSUE THREAD

**Issue by username7171** [AutoViML/AutoViz#36]
Similar project to AutoViz are Sweetviz and Pandas Profiling.

They could export the report as a HTML file.
I wonder if this library also has this function?

**Comment by ghost** [comment]
I am waiting for the same improvement of AutoViz. Cannot suppress the output or save it as html file.

**Comment by AutoViML** [comment]
Ho:You can suppress the output and save all the charts automatically if you set the verbose input flag  to 2. 

You will see all the charts are saved in JPG or PNG format in your local machine just underneath the current directory. 

Please check and let me know.

Thx

Ram
    On Wednesday, March 10, 2021, 4:29:43 PM EST, RalucaBala ***@***.***> wrote:  
 
 


I am waiting for the same improvement of AutoViz. Cannot suppress the output or save it as html file.

**Comment by ghost** [comment]
I was referring to saving the whole output as html not the charts.

**Comment by AutoViML** [comment]
At the moment, there is no plan to save the whole output as HTML file.
I will let you know if there is any change in my plans.
Thanks
Ram

**Comment by AutoViML** [comment]
Hi @sunset1234321 👍 @RalucaBala 👍 
AutoViz now allows you to save all charts in HTML format. They are even dynamic HTML charts since they have widgets that allow you to change them. Take a look at the main  [README page](https://github.com/AutoViML/AutoViz) to see how it works.

I will also add examples in the [Examples page](https://github.com/AutoViML/AutoViz/tree/master/Examples) so you can see it in action.

Hope this helps,
AutoViML team

**Comment by ajay-sk-finarb** [comment]
Is there any way to append all the charts generated in Single HTML rather than multiple HTML files?
