### ISSUE TITLE
Module autoviz not found

### ISSUE THREAD

**Issue by Abh8017** [AutoViML/AutoViz#38]
![image](https://user-images.githubusercontent.com/38239830/116802410-07a58500-ab30-11eb-837a-12f7fa5d943b.png)
`ModuleNotFoundError: No module named 'autoviz'`

Let me know if I am doing anything wrong

**Comment by AutoViML** [comment]
Hi:
It is possible that doing pip install via Jupyter Notebook might be the culprit here.

You should either try on your Jupyter Notebook:
!pip install autoviz

or try in your windows terminal the following:
pip install autoviz

I think that should solve it.
Closing it for now.
Let me know if you need to open it again.
