### ISSUE TITLE
Not able to read or load file. Please check your inputs and try again...

### ISSUE THREAD

**Issue by k-nayak** [AutoViML/AutoViz#63]
pandas ascii encoder does not work for this file. Continuing...
    pandas utf-8 encoder does not work for this file. Continuing...
    pandas iso-8859-1 encoder does not work for this file. Continuing...
    pandas cp1252 encoder does not work for this file. Continuing...
    pandas latin1 encoder does not work for this file. Continuing...
Not able to read or load file. Please check your inputs and try again...

Hello Everyone, this is my first time using Autoviz, after reaing the guide i tried to read a csv dataset and i am getting this error. Is there any way to fix this or shall imake any changes to the csv file before using autoviz. Thanks in advance.

**Comment by k-nayak** [comment]
Shape of your Data Set loaded: (82385, 1)
############## C L A S S I F Y I N G  V A R I A B L E S  ####################
Classifying variables in data set...
    1 Predictors classified...
        No variables removed since no ID or low-information variables found in data set
No continuous variables in this data set. No visualization can be performed
Not able to read or load file. Please check your inputs and try again...

I also got this as an error, i am guessing it has something to do with the dataset. Any response will be appreciated.

**Comment by AutoViML** [comment]
Hello @k-nayak 👍 
It is very simple. AutoViz uses pandas to read your file. Why don't you first read your file using pandas into a dataframe and then send it as input? Since AutoViz is saying that the shape of your dataset is ```(82385,1)``` I assume that the "sep" separator in your file is not comma but it is something else. If you can feed the right separator to AutoViz, it will read it.

Please read the documentation on AutoViz and try Google search next time - there are 100's of articles on Google search that show how to use AutoViz. 

Thanks for trying out AutoViz.
