### ISSUE TITLE
Not able to read or load file using Auto viz

### ISSUE THREAD

**Issue by gbogobabs** [AutoViML/AutoViz#73]
I am having the above error while using autoviz
My target variable is price
i even tried it using empty target variable still same result i dont know the problem
I tried dataframe, still same issue meanwhile i as able to read my data with pandas but autoviz could no
[house_price.zip](https://github.com/AutoViML/AutoViz/files/9125496/house_price.zip)
i attached Zip file of the data because it was large
kindly assist

**Comment by AutoViML** [comment]
Hi @gbogobabs 👍 
You can upgrade to the minor big fix version now:

```
pip install autoviz --upgrade
```

But I noticed that your dataset does not have any numeric vars. So you must first convert at least one or two variables to numeric before using AutoViz since it does not visualize an all-categorical dataset. You can use our other library 'lazytransform' to convert your dataset to numeric.
![house_price](https://user-images.githubusercontent.com/51647480/179543067-65903a9d-b5c4-4ff3-9798-12c746c89bca.png)

Hope this helps.

**Comment by gbogobabs** [comment]
Hello AutovizTeam,

I have been able to do an upgrade on Autoviz
But the second library you recommended (lazytransform), I am having a difficult time installing. I left my laptop for 2 hours still the library did not install. I had to stop the process
I don't know what the issue might be. Kindly assist
I use 8GB RAM and 50GB HDD
________________________________

**Comment by AutoViML** [comment]
Hello @gbogobabs 👍 
You can try reading the installation instructions on this page:
https://github.com/AutoViML/lazytransform

Or you can try using Kaggle or Colab notebooks which are easier to use. Here is a Kaggle notebook that uses LazyTransform:
https://www.kaggle.com/code/rsesha/lazytransform-heartdisease-accuracy-77

**Comment by gbogobabs** [comment]
Hello,
Thank you for your mail
I have the second column which is price as numeric but i will covert some and revert

Thanks
________________________________
