### ISSUE TITLE
Cannot even import autoviz?

### ISSUE THREAD

**Issue by mkumar73** [AutoViML/AutoViz#90]
Not able to even import autoviz after installation. Thought to try it, but doesn't work.

Please see the screenshot below:

![image](https://github.com/AutoViML/AutoViz/assets/14772927/2559ced9-bef9-4bd8-8710-0db8b3793203)
![image](https://github.com/AutoViML/AutoViz/assets/14772927/67b63abc-1842-417f-a060-f7777237b093)
![image](https://github.com/AutoViML/AutoViz/assets/14772927/2ea49dac-1883-4049-bee8-3aa5589f41ba)

**Comment by mkumar73** [comment]
duplicate issue, already raised before by another user.

**Comment by AutoViML** [comment]
PLEASE REMEMBER THAT AUTOVIZ INSTALLS ON COLAB AND IMPORTS WITH ZERO EFFORT. Same story with Kaggle Notebooks where there are thousands of notebooks which use AutoViz. But if you install it via `pip` on your local machine without setting up a separate environment, sometimes, it will clash with your existing versions. Instead, if you choose to install autoviz via `conda` then it will work better. I think there are some versions of bokeh which are messed up. I can't help it if you don't try `conda` or a separate `env`.

Check if your versions are correct:
```bokeh~=2.4.2 (from autoviz)
holoviews~=1.14.9 (from autoviz)
hvplot~=0.7.3 (from autoviz)
panel>=0.12.6 (from autoviz)```

Similarly you can check the public Colab notebook here which runs without a problem.
https://colab.research.google.com/drive/1o1tEz6IyJnPwpFVEs42E16Q0lZXCcJgT?usp=sharing

I am going to close this issue since you need to try these above before filing an issue.
Thanks
Auto Vimal
